Repository AY2324S2-CS2103T-T09-4/tp, pull requests merged in 2024-03, with the labels that each got.

#29 Update DeveloperGuide.md define use cases
  docs/DeveloperGuide.md
Labels: type.documentation, priority.high

#33 Update about us
  docs/AboutUs.md
  docs/images/qinxutan.png
  docs/images/zack-tay.png
Labels: priority.high, toReview

#35 Update user guide for view students and delete student
  docs/UserGuide.md
Labels: priority.high, toReview

#37 Update use cases in developers guide
  docs/DeveloperGuide.md
Labels: priority.high, toReview

#45 Update UserGuide Commands
  docs/UserGuide.md
Labels: type.documentation, priority.high, priority.urgent

#46 Update User Guide remove AB3 docs
  docs/UserGuide.md
Labels: type.documentation

#50 Remove ui elements from DG use cases
  docs/DeveloperGuide.md
Labels: priority.urgent, toReview

#54 Add new Add students' contact
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.feature, priority.high, toReview

#61 Add List Class Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListClassesCommand.java
  src/main/java/seedu/address/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddClassCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListClassesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddClassCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: type.feature, priority.high

#62 Add delete student functionality
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand/DeleteStudentByEmailCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand/DeleteStudentByIdCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand/DeleteStudentByIndexCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteStudentCommandParserTest.java
Labels: type.feature, priority.high, toReview

#67 Fix delete student command directory bug
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentByEmailCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentByIdCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentByIndexCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteStudentCommandParserTest.java
Labels: type.bug, priority.urgent, toMerge

#63 Add command search student
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/SearchStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchStudentCommandParser.java
  src/main/java/seedu/address/model/module/ModuleContainsKeywordPredicate.java
  src/main/java/seedu/address/model/module/TutorialContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/StudentIdContainsKeywordPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/SearchStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchStudentCommandParserTest.java
  src/test/java/seedu/address/model/module/ModuleContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/module/TutorialContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/StudentIdContainsKeywordPredicateTest.java
Labels: type.feature, priority.medium, priority.urgent, toReview

#75 Update Add student command format
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentByEmailCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchStudentCommandParser.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleContainsKeywordPredicate.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/model/module/TutorialContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchStudentCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/module/ModuleContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/module/TutorialClassTest.java
  src/test/java/seedu/address/model/module/TutorialContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/StudentIdContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.feature, priority.high, toMerge, toReview

#65 Save classes to database and Update UI
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalModuleAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/module/TutorialClassTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/ui/JavaFxInitializer.java
Labels: type.feature, priority.high, toReview

#78 UI Testcases
  src/test/java/seedu/address/ui/ModuleCardTest.java
  src/test/java/seedu/address/ui/ModuleListPanelTest.java
Labels: priority.medium, toMerge

#73 Remove find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/SearchStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: priority.medium, toMerge, type.refactor

#85 Update to check email needs to be unique in the list of students
  src/main/java/seedu/address/model/person/Person.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.medium, toMerge, toReview

#68 Add functionality to link students to class command
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByEmailCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByIdCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByIndexCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentByEmailCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentByIdCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentByIndexCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/messages/ModuleMessages.java
  src/main/java/seedu/address/logic/messages/PersonMessages.java
  src/main/java/seedu/address/logic/messages/TutorialClassMessages.java
  src/main/java/seedu/address/logic/parser/AddStudentToClassCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleTutorialPair.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorialClass.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentToClassCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddStudentToClassCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/AddStudentToClassCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialClassTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: type.feature, priority.low, toReview

#86 Update list students command naming convention
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.chore, priority.high, toReview

#91 Fix SearchStudentCommand
  src/main/java/seedu/address/logic/parser/SearchStudentCommandParser.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/StudentIdContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/parser/SearchStudentCommandParserTest.java
  src/test/java/seedu/address/model/person/EmailContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/StudentIdContainsKeywordPredicateTest.java
Labels: type.bug, type.testing

#104 Update naming convention and minor UI fixes
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.high, toReview, type.refactor

#108 Create tutorial teams
  src/main/java/seedu/address/logic/commands/AddTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/model/module/TutorialTeam.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorialClass.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorialTeam.java
  src/test/java/seedu/address/logic/commands/AddStudentToClassCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddStudentToClassCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTeamCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTeamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/module/TutorialTeamTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialClassTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTeamTest.java
Labels: type.feature, priority.high, toReview

#114 UI update
  src/main/resources/view/MainWindow.fxml
Labels: draft

#116 Add command to edit student information
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.feature, priority.high, toReview

#117 Add command to sort student
  src/main/java/seedu/address/logic/commands/SortStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortStudentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/SortStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortStudentCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: type.feature, priority.high, toReview

#126 Update Developer Guide to include search feature
  docs/DeveloperGuide.md
  docs/diagrams/SearchStudentSequence.puml
Labels: type.documentation, priority.low

#124 Add command to add student into existing team in tutorial class.
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByEmailCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByIndexCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByStuIdCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AllocateStudentToTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/model/module/TutorialTeam.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/StudentId.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorialClass.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorialTeam.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/AllocateStudentToTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AllocateStudentToTeamCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialClassTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialTeamTest.java
Labels: priority.high, toMerge, toReview

#127 Add DG section for add student to class
  docs/DeveloperGuide.md
  docs/diagrams/AddStudentToClassSequence.puml
Labels: type.documentation, priority.low, toReview

#122 List students of class command
  src/main/java/seedu/address/logic/commands/ListStudentsOfClassCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListStudentsOfClassCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TutorialClassCard.java
  src/main/resources/images/damith1.png
  src/main/resources/images/damith2.png
  src/main/resources/images/damith3.png
  src/main/resources/images/damith4.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/ListStudentsOfClassCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentToClassCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListStudentsOfClassCommandParserTest.java
Labels: priority.medium, toReview

#129 Update DG and UML
  docs/DeveloperGuide.md
Labels: draft

#131 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.documentation, priority.low, toReview
