Repository AY2324S2-CS2103T-T09-4/tp, pull requests merged in 2024-04, with the labels that each got.

#136 Refactor SortStudentCommand
  src/main/java/seedu/address/logic/commands/sortstudentcommands/SortStudentCommand.java
  src/main/java/seedu/address/logic/commands/sortstudentcommands/SortStudentParameter.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortStudentCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/SortStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/SortStudentCommandParserTest.java
Labels: type.testing, priority.medium, type.refactor

#132 Add Random Team Allocation command
  src/main/java/seedu/address/logic/commands/RandomTeamAllocationCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByEmailCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByIndexCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByStuIdCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RandomTeamAllocationCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/model/module/TutorialTeam.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RandomTeamAllocationCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RandomTeamAllocationCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.medium, toMerge, toReview

#130 Update UML
  docs/diagrams/AddClassSequence.puml
  docs/diagrams/AddTeamSequence.puml
  docs/diagrams/AllocateStudentToTeamSequence.puml
  docs/diagrams/DeleteClassSequence.puml
  docs/diagrams/DeleteModuleSequence.puml
  docs/diagrams/DeleteStudentFromClassSequence.puml
  docs/diagrams/DeleteStudentSequence.puml
  docs/diagrams/DeleteTeamSequence.puml
  docs/diagrams/ListClassSequence.puml
  docs/diagrams/ListStudentsOfClass.puml
  docs/diagrams/SortStudentSequence.puml
Labels: type.documentation, toReview

#138 Update UserGuide.md
  docs/UserGuide.md
  docs/images/cmdguidewin.png
  docs/images/cmdguidewin2.png
Labels: type.documentation, draft

#140 Update UserGuide
  docs/UserGuide.md
  docs/images/cmdwinguide.png
  docs/images/cmdwinguide2.png
Labels: type.documentation, priority.high

#125 View team function
  src/main/java/seedu/address/logic/commands/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsCommand.java
  src/main/java/seedu/address/logic/commands/ViewTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewTeamCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/TutorialTeam.java
  src/main/java/seedu/address/model/module/TutorialTeamName.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TutorialClassCard.java
  src/main/java/seedu/address/ui/TutorialListPanel.java
  src/main/resources/images/damith1.png
  src/main/resources/images/damith2.png
  src/main/resources/images/damith3.png
  src/main/resources/images/logo.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorialClassCard.fxml
  src/main/resources/view/TutorialListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTeamCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ViewTeamCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTeamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewTeamCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/module/TutorialTeamTest.java
Labels: type.feature, priority.medium, draft

#135 Refactor messages
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByEmailCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByIndexCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByStuIdCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentfromclasscommands/DeleteStudentFromClassByIndexCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentfromteamcommands/DeleteStudentFromTeamByEmailCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentfromteamcommands/DeleteStudentFromTeamByIdCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentfromteamcommands/DeleteStudentFromTeamByIndexCommand.java
  src/main/java/seedu/address/logic/messages/ModuleMessages.java
  src/main/java/seedu/address/logic/messages/PersonMessages.java
  src/main/java/seedu/address/logic/messages/TutorialClassMessages.java
  src/main/java/seedu/address/logic/messages/TutorialTeamMessages.java
  src/test/java/seedu/address/logic/commands/AddClassCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/AllocateStudentToTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromClassCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentFromTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.low, toReview

#146 Add class size constraints
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByEmailCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByIdCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByIndexCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassCommand.java
  src/main/java/seedu/address/logic/messages/TutorialClassMessages.java
  src/main/java/seedu/address/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/storage/JsonAdaptedTutorialClass.java
  src/test/java/seedu/address/logic/commands/AddClassCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentToClassCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddClassCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorialClassTest.java
Labels: priority.urgent, toReview

#145 Update ug 1.3
  docs/UserGuide.md
Labels: type.documentation, toReview

#144 Update user guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/sortstudentcommands/SortStudentCommand.java
  src/test/java/seedu/address/ui/MainWindowTest.java
Labels: type.documentation

#142 Fix delete commands not cascading to tutorial teams
  src/main/java/seedu/address/logic/commands/deletestudentcommands/DeleteStudentCommand.java
  src/main/java/seedu/address/model/module/TutorialClass.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/model/module/TutorialClassTest.java
Labels: toReview

#153 Update Testcases
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/AllocateStudentToTeamCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AllocateStudentToTeamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RandomTeamAllocationCommandParserTest.java
Labels: toReview

#235 Fix Bugs
  .github/workflows/gradle.yml
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentsOfClassCommand.java
  src/main/java/seedu/address/logic/commands/RandomTeamAllocationCommand.java
  src/main/java/seedu/address/logic/commands/ViewTeamCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByEmailCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByIdCommand.java
  src/main/java/seedu/address/logic/commands/addstudenttoclasscommands/AddStudentToClassByIndexCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByEmailCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByIndexCommand.java
  src/main/java/seedu/address/logic/commands/allocatestudenttoteamcommands/AllocateStudentToTeamByStuIdCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentfromclasscommands/DeleteStudentFromClassByEmailCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentfromclasscommands/DeleteStudentFromClassByIdCommand.java
  src/main/java/seedu/address/logic/commands/deletestudentfromclasscommands/DeleteStudentFromClassByIndexCommand.java
  src/main/java/seedu/address/logic/parser/AddTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewTeamCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TutorialClassCard.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListStudentsOfClassCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewTeamCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: toMerge, toReview

#239 Fix extra preamble in search_student not triggering invalid command
  src/main/java/seedu/address/logic/parser/SearchStudentCommandParser.java
Labels: toReview

#232 UML Diagrams
  docs/UserGuide.md
  docs/diagrams/AddStudentActivityDiagram.puml
  docs/diagrams/AddStudentSequence.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModuleClassDiagram.puml
  src/main/java/seedu/address/logic/messages/PersonMessages.java
Labels: type.documentation

#241 Reformat UG command summary, add GUI section and minor fixes
  docs/UserGuide.md
  docs/images/Gui.png
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddTeamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTeamCommand.java
  src/main/java/seedu/address/logic/parser/AddTeamCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTeamCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTeamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.high, toReview

#243 Update developer guide to include edit command
  docs/DeveloperGuide.md
  docs/diagrams/EditStudentSequence.puml
Labels: type.documentation, toReview

#246 Update DG functions and other minor UG fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTeamSequence.puml
  docs/diagrams/DeleteStudentSequence.puml
  docs/diagrams/DeleteTeamSequence.puml
Labels: priority.urgent, toReview

#254 Update DG use cases
  docs/DeveloperGuide.md
Labels: priority.urgent, toReview

#258 Update enhancements and design sections
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: priority.urgent, toReview
